name: test

on: workflow_dispatch

jobs:
  test:
    name: Test vulnny action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tjgurwara99/vulnny-action@main
        with:
          go-version: 1.20.6
